modLoader="javafml"
license="MIT"
loaderVersion="[35.1,)"
[[mods]]
modId="terraforged"
displayName="TerraForged"
version="${version}"
authors="dags,Won-Ton"
credits="dags,Won-Ton"
logoFile="terraforged.png"
displayURL="https://terraforged.com"
issueTrackerURL="https://github.com/TerraForged/TerraForged/issues"
description='''
Description:
 A terrain generator!
'''